title: PHS-CPT
logo: https://avatars.githubusercontent.com/u/104660131?s=400&u=5f74a3d1f9ebfc4a9694ff1842b8f6142649c45d&v=4
description: Princeton High School's Competitive Programming Team
theme: jekyll-theme-minimal
